### ISSUE TITLE
Generate SSH Key for cloning repos

### ISSUE THREAD

**Issue by viv-4** [PlaceOS/models#37]
Ideally cloning private repos should be done via ssh, with keys added to the required repos only.

We need a way to either generate an ssh-key pair, or copy the public key of an existing pair, from backoffice.

**Comment by viv-4** [comment]
Just thinking this through a little more,

Core should probably generate the key pair when it starts, if it doesn't already exist (in a volume mount), and Frontends can share this volume. 
So that it is created once and doesn't change.

Then we just need to be able to copy the public key from backoffice to add it to the required repos.

**Comment by KimBurgess** [comment]
There’s a few possibilities for handling this:
1. One key-pair per repo. These can be generated when adding a repo and the public key shown to the user. This could work neatly if we split out the driver and UI build process to an external service. Advantages is this makes it very simple safe to roll keys if required and we’d likely only have a single instance of the service so never need to share private keys between machines.
2. One key-pair per core node.
3. Or, one key-pair per full deploy (shared between all core nodes and repos).

@viv-4 you’re probably more familiar than me, but am I correct in thinking that most repo hosting providers need these keys added at the repo level rather than being able to be added to an org? The only reason I can see for _not_ using a key per repo is to reduce config overhead.

**Comment by caspiano** [comment]
We'll avoid generation of the key on the core side @viv-4 
At the model level, we'll generate a new keypair (if none is passed in during creation) and keep it encrypted server-side.
The public key will be visible to admin/support.

**Comment by caspiano** [comment]
See PlaceOS/compiler#9

**Comment by dukeraphaelng** [comment]
This is related to what I am working on here 
https://github.com/place-technology/portal-licensemanager/issues/16

**Comment by caspiano** [comment]
The build service that is replacing the internal core compilation and the cloning process will only support password-based authentication for git repos
